// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC35vAaeNtl74Y9Yi04DKQwKL8F-CmtT-o',
    appId: '1:65985740707:web:9d0cd93a0efb18c3022416',
    messagingSenderId: '65985740707',
    projectId: 'studentrec-46da7',
    authDomain: 'studentrec-46da7.firebaseapp.com',
    storageBucket: 'studentrec-46da7.appspot.com',
    measurementId: 'G-KVJNTLSQ8X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdEkTrYqzd-EC80Iy87HoQtVyBUNpiNSg',
    appId: '1:65985740707:android:efb2f60b96728454022416',
    messagingSenderId: '65985740707',
    projectId: 'studentrec-46da7',
    storageBucket: 'studentrec-46da7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1L2iHs3tggDdCV1lEF6syd-Qj-VPHfH8',
    appId: '1:65985740707:ios:77fa41a38bf38b97022416',
    messagingSenderId: '65985740707',
    projectId: 'studentrec-46da7',
    storageBucket: 'studentrec-46da7.appspot.com',
    iosClientId: '65985740707-2qiveh5gajppt85n527k6qp0cu23tva9.apps.googleusercontent.com',
    iosBundleId: 'com.example.dbMe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1L2iHs3tggDdCV1lEF6syd-Qj-VPHfH8',
    appId: '1:65985740707:ios:23ad50a971ee3d1c022416',
    messagingSenderId: '65985740707',
    projectId: 'studentrec-46da7',
    storageBucket: 'studentrec-46da7.appspot.com',
    iosClientId: '65985740707-600pev9sistu1ph1jn8ftld1bqqjm5fs.apps.googleusercontent.com',
    iosBundleId: 'com.example.dbMe.RunnerTests',
  );
}
